@authUrl = http://localhost:3000/api/auth
@baseUrl = http://localhost:3000/api/product

### Login User (seeded admin)
# @name login
POST {{authUrl}}/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "AdminPass123!"
}

### Create Product
# @name createProduct
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "name": "Test Product A"
}

### Get All Products (Default)
GET {{baseUrl}}/
Authorization: Bearer {{login.response.body.accessToken}}

### Get All Products (Pagination & Sorting)
GET {{baseUrl}}/?page=1&limit=5&sortBy=name&order=desc
Authorization: Bearer {{login.response.body.accessToken}}

### Search Products
GET {{baseUrl}}/?search=Test
Authorization: Bearer {{login.response.body.accessToken}}

@productId = {{createProduct.response.body.data.id}}

### Get One Product
GET {{baseUrl}}/{{productId}}
Authorization: Bearer {{login.response.body.accessToken}}

### Update Product
PUT {{baseUrl}}/{{productId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "name": "Updated Product Name"
}

### Delete Product
DELETE {{baseUrl}}/{{productId}}
Authorization: Bearer {{login.response.body.accessToken}}
